#!/usr/bin/with-contenv bash

umask 022

exec \
	s6-setuidgid abc python /app/watcher3/watcher.py \
    --address 0.0.0.0 \
    --port 9090 \
    --conf /config/config.cfg \
    --log /config/logs/ \
    --db /config/watcher3.sqlite \
    --plugins /config/plugins/